has.iot/Areas/AircondRaspberry/Controllers/RaspberryController.cs
using has.iot.Components;
using Aircond.Raspberry.Models.System;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNet.SignalR;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Aircond.Raspberry.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using uPLibrary.Networking.M2Mqtt.Messages;
using Kendo.Mvc.Export;
using Telerik.Documents.SpreadsheetStreaming;
using System.IO;
using System.Text;
using Aircond.Raspberry.Components;
using MongoDB.Driver;
using Kendo.Mvc;
using MongoDB.Bson;
using System.Text.RegularExpressions;

namespace Aircond.Raspberry.Controllers
{
    public class RaspberryController : Controller
    {
        // GET: Raspberry
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ConfigService()
        {
            return View();
        }
        public ActionResult Whois()
        {
            var categories = new List<CategoryView_REC>() {
                   new CategoryView_REC() {
                      CategoryName = "Read Only",
                      CategoryID = 1
                  },
                  new CategoryView_REC() {
                      CategoryName = "Write Only",
                      CategoryID = 2
                  },
                  new CategoryView_REC() {
                      CategoryName = "Both",
                      CategoryID = 3
                  }
            };

            ViewData["categories"] = categories;
            ViewData["defaultCategory"] = categories.First();
            return View();
        }

        public ActionResult GetLokkuplist(string Type, string text)
        {
            RaspberryModel oClass = new RaspberryModel();
            var voTable = oClass.GetForLookup(Type, text);
            return Json(voTable, JsonRequestBehavior.AllowGet);
        }

        #region CRUD
        public ActionResult Read([DataSourceRequest]DataSourceRequest poRequest)
        {
            RaspberryModel oClass = new RaspberryModel();
            var vResult = oClass.GetList().ToList();
            return Json(vResult.ToDataSourceResult(poRequest));
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Create([DataSourceRequest]DataSourceRequest poRequest, Raspberry_REC poRecord)
        {
            if ((poRecord != null) && (ModelState.IsValid))
            {
                DatabaseContext oRemoteDB = new DatabaseContext();
                var oTransaction = oRemoteDB.Database.BeginTransaction();
                try
                {
                    RaspberryModel oClass = new RaspberryModel();
                    if (!oClass.Insert(oRemoteDB, poRecord))
                    {
                        ModelState.AddModelError("Error", oClass.ErrorMessage);
                    }
                    oTransaction.Commit();
                }
                catch (Exception ex)
                {
                    oTransaction.Rollback();
                    ModelState.AddModelError("Error", ex.Message);
                }

            }
            return Json(new[] { poRecord }.ToDataSourceResult(poRequest, ModelState));
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Update([DataSourceRequest]DataSourceRequest poRequest, Raspberry_REC poRecord)
        {
            if ((poRecord != null) && (ModelState.IsValid))
            {
                DatabaseContext oRemoteDB = new DatabaseContext();
                var oTransaction = oRemoteDB.Database.BeginTransaction();
                try
                {
                    RaspberryModel oClass = new RaspberryModel();
                    if (!oClass.Update(oRemoteDB, poRecord))
                    {
                        ModelState.AddModelError("Error", oClass.ErrorMessage);
                    }
                    oTransaction.Commit();
                }
                catch (Exception ex)
                {
                    oTransaction.Rollback();
                    ModelState.AddModelError("Error", ex.Message);
                }
            }

            return Json(new[] { poRecord }.ToDataSourceResult(poRequest, ModelState));
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Destroy([DataSourceRequest]DataSourceRequest poRequest, Raspberry_REC poRecord)
        {
            if (poRecord != null)
            {
                DatabaseContext oRemoteDB = new DatabaseContext();
                var oTransaction = oRemoteDB.Database.BeginTransaction();
                try
                {
                    RaspberryModel oClass = new RaspberryModel();
                    if (!oClass.Delete(oRemoteDB, poRecord))
                    {
                        ModelState.AddModelError("Error", oClass.ErrorMessage);
                    }
                    oTransaction.Commit();
                }
                catch (Exception ex)
                {
                    oTransaction.Rollback();
                    ModelState.AddModelError("Error", ex.Message);
                }
            }

            return Json(new[] { poRecord }.ToDataSourceResult(poRequest, ModelState));
        }
        #endregion

        #region object instance
        public ActionResult ObjectRead([DataSourceRequest]DataSourceRequest poRequest, string DeviceID)
        {
            var categories = new List<CategoryView_REC>() {
                   new CategoryView_REC() {
                      CategoryName = "Read Only",
                      CategoryID = 1
                  },
                  new CategoryView_REC() {
                      CategoryName = "Write Only",
                      CategoryID = 2
                  },
                  new CategoryView_REC() {
                      CategoryName = "Both",
                      CategoryID = 3
                  }
            };

            RaspberryModel oClass = new RaspberryModel();
            var vResult = oClass.GetListDataObject(DeviceID).ToList();
            List<RaspberryObject_REC> ListObjt = new List<RaspberryObject_REC>();
            foreach (RaspberryObject_REC objData in vResult)
            {
                objData.Category = categories.Find(f => f.CategoryID == objData.Type);
                ListObjt.Add(objData);
            }
            return Json(ListObjt.ToDataSourceResult(poRequest));
        }
        public ActionResult ObjectReadDLL(string DeviceID, string Type, string text)
        {
            var categories = new List<CategoryView_REC>() {
                   new CategoryView_REC() {
                      CategoryName = "Read Only",
                      CategoryID = 1
                  },
                  new CategoryView_REC() {
                      CategoryName = "Write Only",
                      CategoryID = 2
                  },
                  new CategoryView_REC() {
                      CategoryName = "Both",
                      CategoryID = 3
                  }
            };

            RaspberryModel oClass = new RaspberryModel();
            var vResult = oClass.GetListDLLObject(DeviceID, Type, text).ToList();
            List<RaspberryObject_REC> ListObjt = new List<RaspberryObject_REC>();
            foreach (RaspberryObject_REC objData in vResult)
            {
                objData.Category = categories.Find(f => f.CategoryID == objData.Type);
                objData.ObjectName = objData.ObjectName + ":" + objData.Instance;
                ListObjt.Add(objData);
            }

            return Json(ListObjt, JsonRequestBehavior.AllowGet);
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult ObjectUpdate([DataSourceRequest]DataSourceRequest poRequest, [Bind(Prefix = "models")]IEnumerable<RaspberryObject_REC> poRecord)
        {
            Dictionary<string, string> vsLogMessage = new Dictionary<string, string>();
            DatabaseContext oRemoteDB = new DatabaseContext();
            var oTransaction = oRemoteDB.Database.BeginTransaction();
            try
            {
                RaspberryModel oClass = new RaspberryModel();
                foreach (RaspberryObject_REC voObj in poRecord)
                {
                    voObj.Type = voObj.Category.CategoryID;
                    if (!oClass.ObjectUpdate(oRemoteDB, voObj))
                    {
                        throw new Exception(oClass.ErrorMessage);
                    }
                }
                oTransaction.Commit();


                vsLogMessage.Add("errorcode", "0");
                vsLogMessage.Add("title", "Success");
                vsLogMessage.Add("msg", "Insert Data seccess");
            }
            catch (Exception ex)
            {
                oTransaction.Rollback();
                vsLogMessage.Add("errorcode", "100");
                vsLogMessage.Add("title", "warning");
                vsLogMessage.Add("msg", ex.Message);
            }

            return Json(vsLogMessage, JsonRequestBehavior.DenyGet);
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult updateStatusObj(string[] RecordID, string[] voObject, string DeviceID)
        {
            Dictionary<string, string> vsLogMessage = new Dictionary<string, string>();
            DatabaseContext oRemoteDB = new DatabaseContext();
            var oTransaction = oRemoteDB.Database.BeginTransaction();
            try
            {
                RaspberryModel oClass = new RaspberryModel();
                string voRecordID = (RecordID !=null ) ? string.Join(", ", RecordID) : null;
                if (!oClass.updateStatusObj(oRemoteDB, voRecordID, DeviceID))
                {
                    throw new Exception(oClass.ErrorMessage);
                }
                oTransaction.Commit();

                // begin write to json file
                string targetPathView = Server.MapPath("~/Components/Plugins/Aircond/");

has.iot/Controllers/DeviceManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using has.iot.Models;
using System.Web.Script.Serialization;
using Newtonsoft.Json.Linq;
using Kendo.Mvc.UI;
using has.iot.Models.System;
using Kendo.Mvc.Extensions;
using has.iot.Components;

namespace has.iot.Controllers
{
    [IsLoggedIn]
    public class DeviceManagerController : Controller
    {
        // GET: DeviceManager
        public ActionResult Index()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Create([DataSourceRequest]DataSourceRequest poRequest, Device_REC poRecord)
        {
            if ((poRecord != null) && (ModelState.IsValid))
            {
                DatabaseContext oRemoteDB = new DatabaseContext();
                var oTransaction = oRemoteDB.Database.BeginTransaction();
                try
                {
                    DeviceModel oClass = new DeviceModel();
                    if (!oClass.Insert(oRemoteDB, poRecord))
                    {
                        ModelState.AddModelError("Error", oClass.ErrorMessage);
                    }
                    oTransaction.Commit();
                }
                catch (Exception ex)
                {
                    oTransaction.Rollback();
                    ModelState.AddModelError("Error", ex.Message);
                }

            }
            return Json(new[] { poRecord }.ToDataSourceResult(poRequest, ModelState));
        }

        public ActionResult Read([DataSourceRequest]DataSourceRequest poRequest, string plugin)
        {
            DeviceModel oClass = new DeviceModel();
            var vResult = oClass.GetList().ToList();
            return Json(vResult.ToDataSourceResult(poRequest));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Update([DataSourceRequest]DataSourceRequest poRequest, Device_REC poRecord)
        {
            if ((poRecord != null) && (ModelState.IsValid))
            {
                DatabaseContext oRemoteDB = new DatabaseContext();
                var oTransaction = oRemoteDB.Database.BeginTransaction();
                try
                {
                    DeviceModel oClass = new DeviceModel();
                    if (!oClass.Update(oRemoteDB, poRecord))
                    {
                        ModelState.AddModelError("Error", oClass.ErrorMessage);
                    }
                    oTransaction.Commit();
                }
                catch (Exception ex)
                {
                    oTransaction.Rollback();
                    ModelState.AddModelError("Error", ex.Message);
                }
            }

            return Json(new[] { poRecord }.ToDataSourceResult(poRequest, ModelState));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Destroy([DataSourceRequest]DataSourceRequest poRequest, Device_REC poRecord)
        {
            if (poRecord != null)
            {
                DatabaseContext oRemoteDB = new DatabaseContext();
                var oTransaction = oRemoteDB.Database.BeginTransaction();
                try
                {
                    DeviceModel oClass = new DeviceModel();
                    if (!oClass.Delete(oRemoteDB, poRecord))
                    {
                        ModelState.AddModelError("Error", oClass.ErrorMessage);
                    }
                    oTransaction.Commit();
                }
                catch (Exception ex)
                {
                    oTransaction.Rollback();
                    ModelState.AddModelError("Error", ex.Message);
                }
            }

            return Json(new[] { poRecord }.ToDataSourceResult(poRequest, ModelState));
        }
        public ActionResult GetBrandByPlugin(string pluginID, [DataSourceRequest]DataSourceRequest poRequest)
        {
            List<SelectListItem> listBrand = new List<SelectListItem> { };
            return Json(listBrand, JsonRequestBehavior.AllowGet);
        }

        // SmartSwitch
        public ActionResult GetSmartSwitchLogSum(string DeviceID)
        {
            SmartSwitchModel oClass = new SmartSwitchModel();
            var vResult = oClass.GetDaylyToday(DeviceID).SingleOrDefault();
            return Json(vResult);
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult SmartSwitchLog(SmartSwitchhLog_REC poRecord)
        {
            Dictionary<string, string> vsLogMessage = new Dictionary<string, string>();
            DatabaseContext oRemoteDB = new DatabaseContext();
            var oTransaction = oRemoteDB.Database.BeginTransaction();
            try
            {
                SmartSwitchModel oClass = new SmartSwitchModel();
                if (!oClass.Insert(oRemoteDB, poRecord))
                {
                    ModelState.AddModelError("Error", oClass.ErrorMessage);
                }
                vsLogMessage.Add("errorcode", "0");
                vsLogMessage.Add("title", "Success");
                vsLogMessage.Add("msg", "success");
                oTransaction.Commit();
            }
            catch (Exception ex)
            {
                oTransaction.Rollback();
                vsLogMessage.Add("errorcode", "100");
                vsLogMessage.Add("title", "warning");
                vsLogMessage.Add("msg", ex.Message);
            }
            return Json(vsLogMessage);
        }
    }
}

has.iot/Areas/AircondRaspberry/Views/Raspberry/ConfigService.cshtml
@{
    ViewBag.Title = "Iot Category :: Aircond :: Raspberry Pi :: Config Service";
    ViewBag.TitleBar = "Iot Category :: Aircond :: Raspberry Pi :: Config Service";
    Layout = "~/Views/Shared/_IotCategory.cshtml";
    ViewBag.ExcelName = "SmartSwitch_Espurna_" + DateTime.Now.ToString("yyyyMMddHHmmss");
    string DateFormat = "{0:MM-dd-yyyy HH:mm:ss}";
}

<div class="row">
    <div class="col-md-2">
        <a href="@Url.Action("Index","Raspberry",new { Area="AircondRaspberry" }, null)">
            <div class="card card-form">
                <div class="card-header">
                    <h5>
                        <span class="fa fa-list"></span> List Device
                    </h5>
                </div>
            </div>
        </a>
    </div>
    <div class="col-md-2">
        <a href="@Url.Action("Whois","Raspberry",new { Area="AircondRaspberry" }, null)">
            <div class="card card-form" >
                <div class="card-header">
                    <h5>
                        <span class="fa fa-list"></span> Whois Lookup
                    </h5>
                </div>
            </div>
        </a>
    </div>
    <div class="col-md-2">
        <a href="@Url.Action("ConfigService","Raspberry",new { Area="AircondRaspberry" }, null)">
            <div class="card card-form" style="background-color: #d3e6ff;">
                <div class="card-header">
                    <h5>
                        <span class="fa fa-list"></span> Config Service
                    </h5>
                </div>
            </div>
        </a>
    </div>
</div>

<div class="form-group m-form__group row" style="margin-top:5px;">
    <label for="example-search-input" class="col-3 col-form-label">
        Mqtt Host 
    </label>
    <div class="col-5">
        @(Html.Kendo().TextBox<string>()
            .Name("MQTTHOST")
            .HtmlAttributes(new { style = "width: 100%"})
        )
    </div>
</div>
<div class="form-group m-form__group row" style="margin-top:5px;">
    <label for="example-search-input" class="col-3 col-form-label">
        Patch Config
    </label>
    <div class="col-5">
        @(Html.Kendo().TextBox<string>()
            .Name("PatchFile")
            .HtmlAttributes(new { style = "width: 100%" })
        )
    </div>
</div>
<div class="form-group m-form__group row" style="margin-top:5px;">
    <label for="example-search-input" class="col-3 col-form-label">
        Read Interval (millisecond)
    </label>
    <div class="col-5">
        @(Html.Kendo().NumericTextBox<double>()
            .Name("Interval")
            .Format("#")
            .Placeholder("Enter interval in millisecond")
            .HtmlAttributes(new { style = "width: 100%", title = "numeric" })
        )
    </div>
</div>
<button class="k-button k-primary" onclick="setConfig();">Save</button>

<script type="text/javascript">
    var ws= "";
    $(function () {
    // Start the connection.
        ws = $.connection.realTimeHub;
        $.connection.hub.start().done(function () {
            $.notify("websocket running well", "info",{ position:"bottom-right" });
            getConfig();
        });

        ws.client.Raspberry = function (name, message) {
            if (name == "GetConfig") {
                var data = JSON.parse(message);
                $("#MQTTHOST").val(data.MQTTHOST);
                $("#PatchFile").val(data.PatchFile);
                $("#Interval").data("kendoNumericTextBox").value(parseInt(data.Interval));
            }else if (name == "SetConfig") {
                var data = JSON.parse(message);
                $("#MQTTHOST").val(data.MQTTHOST);
                $("#PatchFile").val(data.PatchFile);
                $("#Interval").data("kendoNumericTextBox").value(parseInt(data.Interval));
                setTimeout(function() {
                  StartService();
                }, 3000);
                
            }
        }
    });

    function getConfig() {
        var voData = {
            cmd: "GetConfig",
            DeviceID: "All",
            ObjType: "",
            value: ""
        };
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Commands", "Raspberry", new { area = "AircondRaspberry" })',
            data: JSON.stringify(voData),
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            beforeSend: function () {

            },
            success: function (result) {
                if (result.msg != "success") {

                }
            },
            error: function (xmlhttprequest, textstatus, message) {

            }
        });
    }
    function setConfig() {
        var voData = {
            cmd: "SetConfig",
            DeviceID: $("#MQTTHOST").val(),
            ObjType: $("#PatchFile").val(),
            value: $("#Interval").val()
        };
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Commands", "Raspberry", new { area = "AircondRaspberry" })',
            data: JSON.stringify(voData),
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            beforeSend: function () {
                $(".category-box").LoadingOverlay("show");
            },
            success: function (result) {
                if (result.msg != "success") {

                }
            },
            error: function (xmlhttprequest, textstatus, message) {

            }
        });
    }

    function StartService() {
        $.ajax({
                url: "@Url.Action("StartService", "Services", new { area = "" })?servicename=HASIOT%20-%20Aircond",
                type: 'POST',
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                beforeSend: function (msg) {

                },
                success: function (result) {
                    console.log(result);
                    if (result.msg == "Running" || result.msg == "Starting") {
                        $.notify("Success Config Saved", "success",{ position:"bottom-right" });
                    } else {
                        $.notify("HASIOT - Aircond Service is " + result.msg, "error",{ position:"bottom-right" });
                    }
                    $(".category-box").LoadingOverlay("hide");
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    alert(jQuery.parseJSON(jqXHR.responseText));
                },
                async: false,
                processData: false
            });
    }
</script>

has.iot/Areas/AircondRaspberry/Views/Raspberry/DataLog.cshtml
@{
    ViewBag.TitleBar = "Aircond - Data Log";
    ViewBag.Title = "Aircond - Data Log";
    ViewBag.ExcelName = "Aircond" + DateTime.Now.ToString("yyyyMMddHHmmss");
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="body-content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Filter
                </div>
                <div class="card-body">
                    <div class="form-group">
                        Start Time <br />
                        @Html.Kendo().DateTimePicker().Name("StartTime").Format("dd-MMM-yyyy HH:mm").Interval(1)
                    </div>
                    <div class="form-group">
                        End Time <br />
                        @Html.Kendo().DateTimePicker().Name("EndTime").Format("dd-MMM-yyyy HH:mm").Interval(1)
                    </div>
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary" id="btn-search" onclick="Find()">Find</button>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <form action="@Url.Action("ExportServer", "Raspberry")" method="POST" id="form_export">
                <input type="hidden" id="export-data" name="option" />
                <input type="hidden" id="export-request" name="poRequest" />
                <input style="display:none;" type="submit" class="k-button ExportAll" data-format="xlsx" data-title="Title1" value="Export All to Excel" />
            </form>
            @(Html.Kendo().Grid<Aircond.Raspberry.Models.RaspberryDataLog_REC>()
                .Name("grid")
                .ToolBar(t =>
                {
                    t.Template(@<text>
                    <div class="float-left">
                        <a style="margin-top:3px;" class="k-button k-button-icontext k-grid-Export to excel" href="#" id="ExportAll">Export to excel</a>
                    </div>
                    <div class="float-right">
                        Auto-Refresh: 
                        <input type='number' id='tbInterval' class='k-textbox' onblur='refreshGrid(this);' placeholder="seconds" />
                    </div>
                    </text>);
                })
                .Columns(columns =>
                {
                    columns.Bound(c => c.RecordTimestamp).Format("{0:dd-MMM-yyyy HH:mm:ss}").Filterable(f => f.Cell(c => c.ShowOperators(false)).Enabled(false)).Width(100);
                    columns.Bound(c => c.ObjectName).Filterable(f => f.Cell(c => c.ShowOperators(false).Operator("contains").SuggestionOperator(FilterType.Contains))).Width(100);
                    columns.Bound(c => c.InstanceID).Filterable(f => f.Cell(c => c.ShowOperators(false).Operator("contains").SuggestionOperator(FilterType.Contains))).Width(100);
                    columns.Bound(c => c.DeviceID).Filterable(f => f.Cell(c => c.ShowOperators(false).Operator("contains").SuggestionOperator(FilterType.Contains))).Width(100);
                    columns.Bound(c => c.PresentValue).Filterable(f => f.Cell(c => c.ShowOperators(false).Operator("contains").SuggestionOperator(FilterType.Contains))).Width(100);
                })
                .DataSource(ds => ds
                    .Ajax()
                    .Model(m => m.Id(r => r.RecordID))
                    .PageSize(30)
                    .Read(r => r.Action("GetListDataLog", "Raspberry"))
                    .Sort(sort => sort.Add("RecordTimestamp").Descending())
                )
                .Excel(excel => excel
                .AllPages(true)
                .FileName(@ViewBag.ExcelName + ".xlsx")
                .Filterable(true)
                )
                .Selectable()
                .Filterable(a => a.Mode(GridFilterMode.Row))
                .HtmlAttributes(new { style = "height:550px;" })
                .Pageable(pageable => pageable
                .Refresh(true)
                .PageSizes(true)
                .ButtonCount(5))
                .Reorderable(r => r.Columns(true))
                .Resizable(r => r.Columns(true))
                .Sortable()
                .Scrollable()
                .AutoBind(false)
                )
        </div>
    </div>
</div>
@(Html.Kendo().Window()
    .HtmlAttributes(new { style = "display:none;height:500px" })
    .Name("window")
    .Title("Payload")
    .Content(@<text>
        <pre id="payload_view"></pre>
    </text>)
    .Modal(true)
    .Draggable()
    .Resizable()
    .Width(600)
    .Actions(actions => actions.Pin().Minimize().Maximize().Close())
)
<script type="text/javascript">
    var refreshGridInterval = null;
    var form = document.getElementById("form_export");
    $("#ExportAll").click(function () {
        @*var grid = $("#grid").data("kendoGrid");
        var options = {
            format: "csv",
            title: "Aircond_ALL_@DateTime.Now.ToString("yyyyMMdd")"
        }
        console.log(grid.columns);
        $("#export-model").val(encodeURIComponent(JSON.stringify(grid.columns)));
        $("#export-data").val(encodeURIComponent(JSON.stringify(options)));
        $("#export-ds").val(encodeURIComponent(JSON.stringify(grid.dataSource)));

        var parameterMap = grid.dataSource.transport.parameterMap;
        var data = parameterMap({ sort: grid.dataSource.sort(), filter: grid.dataSource.filter(), group: grid.dataSource.group() });
        $("#export-request").val(encodeURIComponent(JSON.stringify(data)));
        form.submit();*@
        var grid = $("#grid").data("kendoGrid");
        var parameterMap = grid.dataSource.transport.parameterMap;
        var options = {
            format: "csv",
            title: "Aircond_ALL_@DateTime.Now.ToString("yyyyMMdd")"
        }
        var request = parameterMap(
            {
                sort: grid.dataSource.sort(),
                filter: grid.dataSource.filter(),
                group: grid.dataSource.group(),
            }
        );
        var datas = {
            transport: grid.dataSource.transport.options.read.data,
            options: options,
            columns: grid.columns,
        };
       $.ajax({
            url: "@Url.Action("ExportServer", "Raspberry")",
            data: kendo.stringify($.extend(datas, request)),
            contentType: 'application/json; charset=utf-8',
            type: "POST",
           beforeSend: function () {
               $(".loading-spinner").css("display", "block");
           },
           success: function (result) {
               $(".loading-spinner").css("display", "none");
               window.open(
                   base_url + '@Aircond.Raspberry.Components.Constants.ExportDirectory' + result.filename,
                   '_blank' // <- This is what makes it open in a new window.
               );
            }
        });
    });
    var ws3D = "";
    $(function () {
        //ws3D = $.connection.realTimeHub;
        //$.connection.hub.start().done(function () {

        //});
        //ws3D.client.Raspberry = function (name, message) {
        //    console.log(message);
        //    if (name == "DataLog") {
        //        $("#grid").data("kendoGrid").dataSource.read();
        //    }
        //}
        $("#StartTime").data("kendoDateTimePicker").value("@DateTime.Now.ToString("yyyy-MM-dd 00:00:00")");
        $("#EndTime").data("kendoDateTimePicker").value("@DateTime.Now.AddDays(1).ToString("yyyy-MM-dd 00:00:00")");
        Find();
    });
    function Find() {
        var grid = $("#grid").data("kendoGrid");
        var voData = {
            StartTime: $("#StartTime").data("kendoDateTimePicker").value(),
            EndTime: $("#EndTime").data("kendoDateTimePicker").value(),
        };

        grid.dataSource.transport.options.read.type = "POST";
        grid.dataSource.transport.options.read.data = voData;
        grid.dataSource.transport.options.read.url = '@Url.Action("GetListDataLog", "Raspberry")';
        grid.dataSource.read();
    }
    function refreshGrid(e) {
        const value = $(e).val();
        const intval_time = value * 1000;
        if (value != "") {
            if (value == 0) {
                clearInterval(refreshGridInterval);
            } else {
                clearInterval(refreshGridInterval);
                refreshGridInterval = setInterval(function () {
                    $("#grid").data("kendoGrid").dataSource.read();
                }, intval_time);
            }
        } else {
            clearInterval(refreshGridInterval);
        }
    }
    function viewPayload(e) {
        var grid = $("#grid").data("kendoGrid");
        var dataitem = grid.dataItem(e.closest("tr"));
        var payload = JSON.parse(dataitem.Payload);
        document.getElementById("payload_view").innerHTML = JSON.stringify(payload, undefined, 2);
        $("#window").data("kendoWindow").open().center();
    }
</script>