has.iot/Controllers/IotCategoryController.cs
using has.iot.Components;
using has.iot.Models;
using has.iot.Models.System;
using RabbitMQ.Client;
using RabbitMQ.Client.Events;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace has.iot.Controllers
{
    [IsLoggedIn]
    public class IotCategoryController : Controller
    {
        public ActionResult Index()
        {
            Category oClass = new Category();
            var vResult = oClass.GetList().ToList();
            ViewData["Data"] = vResult;
            return View();
        }
        public ActionResult Brands(string Category)
        {
            Brands oClass = new Brands();
            var vResult = oClass.GetList(Category).ToList();
            ViewData["Data"] = vResult;
            return View();
        }
        public ActionResult GetBrands()
        {
            Brands oClass = new Brands();
            var vResult = oClass.GetListBrand()
                .GroupBy(w => w.CategoryID)
                .Select(grp => grp.Take(1).SingleOrDefault()).ToList();
            return Json(vResult,JsonRequestBehavior.AllowGet);
        }
        public ActionResult RemovePlugin(string ID)
        {
            Dictionary<string, string> vsLogMessage = new Dictionary<string, string>();
            try
            {
                Category oClass = new Category();
                Category_REC voPlugin = new Category_REC();
                voPlugin.CategoryID = ID.Replace(" ", String.Empty);
                oClass.Delete(voPlugin);

                // Check if file exists with its full path    
                string targetPathDLL = Server.MapPath("~/bin/" + voPlugin.CategoryID + ".dll");
                string targetPathDLLConf = Server.MapPath("~/bin/" + voPlugin.CategoryID + ".dll.config");
                if (System.IO.File.Exists(targetPathDLL))
                {
                    System.IO.File.Delete(targetPathDLL);
                }
                if (System.IO.File.Exists(targetPathDLLConf))
                {
                    System.IO.File.Delete(targetPathDLLConf);
                }

                vsLogMessage.Add("errorcode", "0");
                vsLogMessage.Add("title", "Success");
                vsLogMessage.Add("msg", "Plugin Removed");
            }
            catch (Exception ex)
            {
                vsLogMessage.Add("errorcode", "100");
                vsLogMessage.Add("title", "warning");
                vsLogMessage.Add("msg", ex.Message);
            }
            return Json(vsLogMessage, JsonRequestBehavior.AllowGet);
        }

    }
}

has.iot/Views/IotCategory/Brands.cshtml
@using has.iot.Models;
@{
    ViewBag.Title = "IoT Category :: " + Request.Params["Category"];
    ViewBag.TitleBar = "IoT Category - " + Request.Params["Category"];
    Layout = "~/Views/Shared/_IotCategory.cshtml";
    IList<Brands_REC> DataList = ViewData["Data"] as IList<Brands_REC>;
}
<div class="row">
    @foreach (Brands_REC Data in DataList)
    {
        <div class="col-md-3">
            <a href="@Url.Action("Index",Data.BrandName.Replace(" ",""),new { Area=Data.CategoryID+Data.BrandName.Replace(" ","") }, null)">
                <div class="card card-form">
                    <div class="card-body align-center">
                        <img src="@Url.Content("~/Content/img/"+Data.Image)" class="category-image" />
                    </div>
                </div>
            </a>
        </div>
    }
</div>
<script type="text/javascript">
    function removePlugin(ID) {
        var r = confirm("Remove this plugin!");
        if (r == true) {
            var voData = {
                ID: ID
            };
            $.ajax({
                type: 'POST',
                url: '@Url.Action("RemovePlugin", "IotCategory")',
                data: JSON.stringify(voData),
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                beforeSend: function () {

                },
                success: function (result) {
                    if (result.errorcode < 1) {
                        alert(result.msg);
                        setTimeout(function () {
                            $('#exampleModal').modal('toggle');
                            window.location.replace('@Url.Action("Index", "IotCategory")');
                        }, 500);
                    } else {
                        alert(result.msg);
                    }
                }
            });
        }
    }
</script>

has.iot/Views/IotCategory/Index.cshtml
@{
    ViewBag.Title = "Iot Category";
    ViewBag.TitleBar = "Iot Category";
    List<has.iot.Models.System.Category_REC> DataList = ViewData["Data"] as List<has.iot.Models.System.Category_REC>;
}
<div class="category-content">
    <div class="row">
        <div class="col-md-3 border-iotcategory-menu">
            <ul class="list-category">
                <li class="add-category">
                    <h5>Add Category</h5>
                    @(Html.Kendo().Upload()
                                .Name("files").HtmlAttributes(new { @class = "btn btn-primary" })
                                .Async(a => a
                                    .Save("UploadFile", "Upload")
                                    .Remove("Remove", "Upload")
                                    .AutoUpload(true)
                                ).Messages(m => m.Select("Choose File"))
                                .Events(events => events
                                    .Success("onSuccess1")
                                )
                                .Validation(validation => validation.AllowedExtensions(new string[] { ".zip" }).MaxFileSize(300000)).Multiple(false)
                    )
                </li>
                @foreach (has.iot.Models.System.Category_REC Data in DataList)
                {
                    <li>
                        <a href="@Url.Action("Brands", "IoTCategory", new { Area="",Category=Data.CategoryID })">
                            <img width="20" src="@Url.Content("~/Content/img/"+Data.Image)" />
                            @Data.CategoryName
                        </a>
                    </li>
                }

            </ul>
        </div>
        <div class="col-md-9 category-box border-bottom">
            <div class="row col-md-12">
                @*
                @foreach (has.iot.Models.System.Category_REC Data in DataList)
                {
                    <div class="col-md-3">
                        <div class="card card-form">
                            <div class="card-header">
                                <h5>@Data.CategoryName <small class="float-sm-right"> <i onclick="removePlugin('@Data.CategoryID');" class="fa fa-trash" style="border: grey solid 1px; padding: 5px; border-radius: 3px; cursor: pointer;"></i></small></h5>
                            </div>
                            <div class="card-body align-center">
                                <span class="helper-box">&nbsp;</span>
                                <img src="@Url.Content("~/Content/img/"+Data.Image)" class="category-image" />
                            </div>
                        </div>
                    </div>
                }
                *@
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#files").closest(".k-upload-button").addClass("btn btn-primary btn-upload-plugin");
        $("#files").closest(".k-upload-button").removeClass("k-button");
    });
    
    function removePlugin(ID) {
        var r = confirm("Remove this plugin!");
        if (r == true) {
            var voData = {
                ID: ID
            };
            $.ajax({
                type: 'POST',
                url: '@Url.Action("RemovePlugin", "IotCategory")',
                data: JSON.stringify(voData),
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                beforeSend: function () {

                },
                success: function (result) {
                    if (result.errorcode < 1) {
                        alert(result.msg);
                        setTimeout(function () {
                            $('#exampleModal').modal('toggle');
                            window.location.replace('@Url.Action("Index", "IotCategory")');
                        }, 500);
                    } else {
                        alert(result.msg);
                    }
                }
            });
        }
    }
    function onSuccess1(e) {
        if (e.operation == "upload") {
            console.log(e);
            if (e.response.errorcode == "0") {
                alert(e.response.msg);
                setTimeout(function () {
                    window.location.replace('@Url.Action("Index", "IotCategory")');
                }, 500);
            } else {
                alert(e.response.msg);
            }
        } else if (e.operation == "remove") {
        }
    }
</script>