has.iot/Areas/SmartSwitchEspurna/Controllers/EspurnaController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using has.iot.Components;
using Kendo.Mvc.Export;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNet.SignalR;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SmartSwitch.Espurna.Components;
using SmartSwitch.Espurna.Models;
using SmartSwitch.Espurna.Models.System;
using Telerik.Documents.SpreadsheetStreaming;
using uPLibrary.Networking.M2Mqtt.Messages;
using MongoDB.Driver;
using MongoDB.Bson;
using Kendo.Mvc;
using System.Text.RegularExpressions;

namespace SmartSwitch.Espurna.Controllers
{
    public class EspurnaController : Controller
    {
        // GET: Espurna
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Log_Read([DataSourceRequest]DataSourceRequest poRequest, string DeviceID)
        {
            EspurnaModel oClass = new EspurnaModel();
            var vResult = oClass.GetLogList(DeviceID).ToList();
            return Json(vResult.ToDataSourceResult(poRequest));
        }

        #region SQL CRUD
        public ActionResult ReadSql([DataSourceRequest]DataSourceRequest poRequest)
        {
            EspurnaModel oClass = new EspurnaModel();
            var vResult = oClass.GetList().ToList();
            return Json(vResult.ToDataSourceResult(poRequest));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult CreateSql([DataSourceRequest]DataSourceRequest poRequest, Espurna_REC poRecord)
        {
            if ((poRecord != null) && (ModelState.IsValid))
            {
                DatabaseContext oRemoteDB = new DatabaseContext();
                var oTransaction = oRemoteDB.Database.BeginTransaction();
                try
                {
                    EspurnaModel oClass = new EspurnaModel();
                    if (!oClass.Insert(oRemoteDB, poRecord))
                    {
                        ModelState.AddModelError("Error", oClass.ErrorMessage);
                    }
                    oTransaction.Commit();
                }
                catch (Exception ex)
                {
                    oTransaction.Rollback();
                    ModelState.AddModelError("Error", ex.Message);
                }

            }
            return Json(new[] { poRecord }.ToDataSourceResult(poRequest, ModelState));
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult UpdateSql([DataSourceRequest]DataSourceRequest poRequest, Espurna_REC poRecord)
        {
            if ((poRecord != null) && (ModelState.IsValid))
            {
                DatabaseContext oRemoteDB = new DatabaseContext();
                var oTransaction = oRemoteDB.Database.BeginTransaction();
                try
                {
                    EspurnaModel oClass = new EspurnaModel();
                    if (!oClass.Update(oRemoteDB, poRecord))
                    {
                        ModelState.AddModelError("Error", oClass.ErrorMessage);
                    }
                    oTransaction.Commit();
                }
                catch (Exception ex)
                {
                    oTransaction.Rollback();
                    ModelState.AddModelError("Error", ex.Message);
                }
            }

            return Json(new[] { poRecord }.ToDataSourceResult(poRequest, ModelState));
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult DestroySql([DataSourceRequest]DataSourceRequest poRequest, Espurna_REC poRecord)
        {
            if (poRecord != null)
            {
                DatabaseContext oRemoteDB = new DatabaseContext();
                var oTransaction = oRemoteDB.Database.BeginTransaction();
                try
                {
                    EspurnaModel oClass = new EspurnaModel();
                    if (!oClass.Delete(oRemoteDB, poRecord))
                    {
                        ModelState.AddModelError("Error", oClass.ErrorMessage);
                    }
                    oTransaction.Commit();
                }
                catch (Exception ex)
                {
                    oTransaction.Rollback();
                    ModelState.AddModelError("Error", ex.Message);
                }
            }

            return Json(new[] { poRecord }.ToDataSourceResult(poRequest, ModelState));
        }
        #endregion

        #region MongoDB CRUD
        public ActionResult Read([DataSourceRequest]DataSourceRequest poRequest, FilterDate filter_date)
        {
            IMongoDatabase database = Constants.MongoClient.GetDatabase("IoT");
            IMongoCollection<SmartDevices_REC> Collections = database.GetCollection<SmartDevices_REC>("SmartDevices");

            int skip = (poRequest.Page * poRequest.PageSize) - poRequest.PageSize;
            int limit = poRequest.PageSize;

            var ds = new List<SmartDevices_REC>().ToDataSourceResult(poRequest);

            var filter_mongo = new BsonDocument();

            if (filter_date.StartTime != DateTime.MinValue && filter_date.EndTime != DateTime.MinValue)
            {
                Dictionary<string, object> obj_filter = new Dictionary<string, object>();
                obj_filter.Add("RecordTimestamp", new BsonDocument() {
                    { "$gte", DateTime.Parse(filter_date.StartTime.ToString("yyyy-MM-dd HH:mm:00")) },
                    { "$lte", DateTime.Parse(filter_date.EndTime.ToString("yyyy-MM-dd HH:mm:00")) }
                });
                filter_mongo.AddRange(obj_filter);
            }

            var sort_mongo = new BsonDocument();
            if (poRequest.Filters.Count > 0)
            {
                foreach (var filter in poRequest.Filters)
                {
                    if (filter is FilterDescriptor)
                    {
                        FilterDescriptor filt = (FilterDescriptor)filter;
                        Dictionary<string, object> obj_filter = new Dictionary<string, object>();
                        obj_filter.Add(filt.Member, BsonRegularExpression.Create(new Regex(filt.Value.ToString(), RegexOptions.IgnoreCase)));
                        filter_mongo.AddRange(obj_filter);
                    }
                    else
                    {
                        FilterDescriptor filt = GlobalFunction.KendoChangeComposite(((CompositeFilterDescriptor)filter).FilterDescriptors);
                        Dictionary<string, object> obj_filter = new Dictionary<string, object>();
                        obj_filter.Add(filt.Member, BsonRegularExpression.Create(new Regex(filt.Value.ToString(), RegexOptions.IgnoreCase)));
                        filter_mongo.AddRange(obj_filter);
                    }
                }
            }

            if (poRequest.Sorts.Count > 0)
            {
                foreach (SortDescriptor sort in poRequest.Sorts)
                {
                    Dictionary<string, object> obj_sort = new Dictionary<string, object>();
                    if (sort.SortDirection == System.ComponentModel.ListSortDirection.Ascending)
                        obj_sort.Add(sort.Member, 1);
                    else
                        obj_sort.Add(sort.Member, -1);

                    sort_mongo.AddRange(obj_sort);
                }
            }

            List<SmartDevices_REC> oTable = Collections.Find(filter_mongo).Sort(sort_mongo).Skip(skip).Limit(limit).ToList();
            ds.Data = oTable.Where(x => x.Category == "Smartlight").ToList();
            ds.Total = Convert.ToInt32(Collections.Find(filter_mongo).CountDocuments());

            var jsonResult = Json(ds);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Create([DataSourceRequest]DataSourceRequest poRequest, SmartDevices_REC poRecord)
        {
            if ((poRecord != null) && (ModelState.IsValid))
            {
                DatabaseContext oRemoteDB = new DatabaseContext();
                var oTransaction = oRemoteDB.Database.BeginTransaction();

                IMongoDatabase database = Constants.MongoClient.GetDatabase("IoT");
                IMongoCollection<SmartDevices_REC> Collections = database.GetCollection<SmartDevices_REC>("SmartDevices");
                try
                {
                    SmartDevices_REC voData = new SmartDevices_REC();
                    voData.RecordTimestamp = DateTime.Now;
                    voData.DeviceID = poRecord.DeviceID;
                    voData.DeviceName = poRecord.DeviceName;
                    voData.IPAddress = poRecord.IPAddress;
                    voData.ObjectName = poRecord.ObjectName;
                    voData.Location = poRecord.Location;
                    voData.SwitchNo = poRecord.SwitchNo;
                    voData.LightController = poRecord.LightController;
                    voData.Category = "Smartlight";
                    voData.Relay = 0;
                    Collections.InsertOne(voData);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("Error", ex.Message);
                }

            }
            return Json(new[] { poRecord }.ToDataSourceResult(poRequest, ModelState));
        }
        public ActionResult Update([DataSourceRequest]DataSourceRequest poRequest, SmartDevices_REC poRecord)
        {
            if ((poRecord != null) && (ModelState.IsValid))
            {
                DatabaseContext oRemoteDB = new DatabaseContext();
                var oTransaction = oRemoteDB.Database.BeginTransaction();

                IMongoDatabase database = Constants.MongoClient.GetDatabase("IoT");
                IMongoCollection<SmartDevices_REC> Collections = database.GetCollection<SmartDevices_REC>("SmartDevices");

has.iot/Areas/SmartSwitchEspurna/Views/Espurna/DataLog.cshtml
@{
    ViewBag.TitleBar = "Smart Light - Data Log";
    ViewBag.Title = "Smart Light - Data Log";
    ViewBag.ExcelName = "Smart Light" + DateTime.Now.ToString("yyyyMMddHHmmss");
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="body-content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Filter
                </div>
                <div class="card-body">
                    <div class="form-group">
                        Start Time <br />
                        @Html.Kendo().DateTimePicker().Name("StartTime").Format("dd-MMM-yyyy HH:mm").Interval(1)
                    </div>
                    <div class="form-group">
                        End Time <br />
                        @Html.Kendo().DateTimePicker().Name("EndTime").Format("dd-MMM-yyyy HH:mm").Interval(1)
                    </div>
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary" id="btn-search" onclick="Find()">Find</button>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <form action="@Url.Action("ExportServer", "Espurna")" method="POST" id="form_export">
            <input type="hidden" id="export-data" name="data" />
            <input type="hidden" id="export-model" name="model" />
            <input style="display:none;" type="submit" class="k-button ExportAll" data-format="xlsx" data-title="Title1" value="Export All to Excel" />
        </form>
            @(Html.Kendo().Grid<SmartSwitch.Espurna.Models.EspurnaDataLog_REC>()
            .Name("grid")
            .ToolBar(t =>
            {
                t.Template(@<text>
            <div class="float-left">
                <a style="margin-top:3px;" class="k-button k-button-icontext k-grid-Export to excel" href="#" id="ExportAll">Export to excel</a>
            </div>
            <div class="float-right">
                Auto-Refresh:
                <input type='number' id='tbInterval' class='k-textbox' onblur='refreshGrid(this);' placeholder="seconds" />
            </div>
                </text>);
            })
            .Columns(columns =>
            {
                columns.Bound(c => c.RecordTimestamp).Format("{0:dd-MMM-yyyy HH:mm:ss}").Filterable(f => f.Cell(c => c.ShowOperators(false)).Enabled(false)).Width(30);
                columns.Bound(c => c.DeviceID).Filterable(f => f.Cell(c => c.ShowOperators(false).Operator("contains").SuggestionOperator(FilterType.Contains))).Width(90);
                columns.Bound(c => c.ActivePower).Title("Active Power (kwh)").Filterable(f => f.Cell(c => c.ShowOperators(false).Enabled(false))).Width(90);
            })
            .DataSource(ds => ds
                .Ajax()
                .Model(m => m.Id(r => r._id))
                .PageSize(30)
                .Read(r => r.Action("GetListDataLog", "Espurna"))
                .Sort(sort => sort.Add("RecordTimestamp").Descending())
            )
            .Excel(excel => excel
            .AllPages(true)
            .FileName(@ViewBag.ExcelName + ".xlsx")
            .Filterable(true)
            )
            .Selectable()
            .Filterable(a => a.Mode(GridFilterMode.Row))
            .HtmlAttributes(new { style = "height:550px;" })
            .Pageable(pageable => pageable
            .Refresh(true)
            .PageSizes(true)
            .ButtonCount(5))
            .Reorderable(r => r.Columns(true))
            .Resizable(r => r.Columns(true))
            .Sortable()
            .Scrollable()
            .AutoBind(false)
            )
        </div>
    </div>
</div>
@(Html.Kendo().Window()
    .HtmlAttributes(new { style = "display:none;height:500px" })
    .Name("window")
    .Title("Payload")
    .Content(@<text>
        <pre id="payload_view"></pre>
    </text>)
    .Modal(true)
    .Draggable()
    .Resizable()
    .Width(600)
    .Actions(actions => actions.Pin().Minimize().Maximize().Close())
)
<script type="text/javascript">
    var refreshGridInterval = null;
    var form = document.getElementById("form_export");
    $("#ExportAll").click(function () {
        var grid = $("#grid").data("kendoGrid");
        var parameterMap = grid.dataSource.transport.parameterMap;
        var options = {
            format: "csv",
            title: "Smartlight_ALL_@DateTime.Now.ToString("yyyyMMdd")"
        }
        var request = parameterMap(
            {
                sort: grid.dataSource.sort(),
                filter: grid.dataSource.filter(),
                group: grid.dataSource.group(),
            }
        );
        var datas = {
            transport: grid.dataSource.transport.options.read.data,
            options: options,
            columns: grid.columns,
        };
       $.ajax({
            url: "@Url.Action("ExportServer", "Espurna")",
            data: kendo.stringify($.extend(datas, request)),
            contentType: 'application/json; charset=utf-8',
           type: "POST",
           beforeSend: function () {
               $(".loading-spinner").css("display", "block");
           },
           success: function (result) {
               $(".loading-spinner").css("display", "none");
               window.open(
                   base_url + '@SmartSwitch.Espurna.Components.Constants.ExportDirectory' + result.filename,
                   '_blank' // <- This is what makes it open in a new window.
               );
            }
        });
    });
    var ws3D = "";
    $(function () {
        //ws3D = $.connection.realTimeHub;
        //$.connection.hub.start().done(function () {

        //});
        //ws3D.client.Raspberry = function (name, message) {
        //    console.log(message);
        //    if (name == "DataLog") {
        //        $("#grid").data("kendoGrid").dataSource.read();
        //    }
        //}
        $("#StartTime").data("kendoDateTimePicker").value("@DateTime.Now.ToString("yyyy-MM-dd 00:00:00")");
        $("#EndTime").data("kendoDateTimePicker").value("@DateTime.Now.AddDays(1).ToString("yyyy-MM-dd 00:00:00")");
        Find();
    });
    function Find() {
        var grid = $("#grid").data("kendoGrid");
        var voData = {
            StartTime: $("#StartTime").data("kendoDateTimePicker").value(),
            EndTime: $("#EndTime").data("kendoDateTimePicker").value(),
        };

        grid.dataSource.transport.options.read.type = "POST";
        grid.dataSource.transport.options.read.data = voData;
        grid.dataSource.transport.options.read.url = '@Url.Action("GetListDataLog", "Espurna")';
        grid.dataSource.read();
    }
    function refreshGrid(e) {
        const value = $(e).val();
        const intval_time = value * 1000;
        if (value != "") {
            if (value == 0) {
                clearInterval(refreshGridInterval);
            } else {
                clearInterval(refreshGridInterval);
                refreshGridInterval = setInterval(function () {
                    $("#grid").data("kendoGrid").dataSource.read();
                }, intval_time);
            }
        } else {
            clearInterval(refreshGridInterval);
        }
    }
    function viewPayload(e) {
        var grid = $("#grid").data("kendoGrid");
        var dataitem = grid.dataItem(e.closest("tr"));
        var payload = JSON.parse(dataitem.Payload);
        document.getElementById("payload_view").innerHTML = JSON.stringify(payload, undefined, 2);
        $("#window").data("kendoWindow").open().center();
    }
</script>